return {
  kind = {
    Text = " ",
    Method = "m ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = "",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
  type = {
    Array = " ",
    Number = " ",
    String = " ",
    Boolean = "蘒 ",
    Object = " ",
  },
  documents = {
    File = " ",
    Files = " ",
    Folder = " ",
    OpenFolder = " ",
  },
  git = {
    Add = "",
    Mod = "柳",
    Remove = "",
    Ignore = "",
    Rename = "",
    Diff = "",
    Repo = "",
    Octoface = "",
  },
  ui = {
    Ellipsis = "",
    Lock = " ",
    Circle = " ",
    BigCircle = " ",
    BigUnfilledCircle = " ",
    Close = " ",
    NewFile = "",
    Search = "",
    Lightbulb = "",
    Project = "",
    Dashboard = "",
    History = "",
    Comment = "",
    Bug = "",
    Code = "",
    Telescope = "",
    Gear = "",
    Package = "",
    List = "",
    SignIn = "",
    Check = "",
    Fire = "",
    Note = "",
    BookMark = "",
    Pencil = "",
    ChevronRight = ">",
    Table = "",
    Calendar = "",
  },
  diagnostics = {
    Error = "",
    Warning = "",
    Information = "󰌶",
    Question = "",
    Hint = "󰌶",
  },
  misc = {
    Robot = "ﮧ",
    Squirrel = "",
    Tag = "",
    Watch = "",
  },
}
